# Generated by Django 5.0 on 2023-12-31 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(choices=[('2023', '2023-2024'), ('2024', '2024-2025'), ('2025', '2025-2026')], default='2023', max_length=10)),
                ('section', models.CharField(max_length=20, null=True)),
                ('strand', models.CharField(choices=[('ICT', 'ICT')], default='ICT', max_length=10)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
