# Generated by Django 5.0 on 2023-12-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='principal_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='track',
            field=models.CharField(choices=[('TVL', 'TVL')], default='TVL', max_length=10),
        ),
    ]
