# Generated by Django 5.0 on 2024-01-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', '1st Quarter'), ('2', '2nd Quarter'), ('3', '3rd Quarter'), ('4', '4th Quarter')], default='1', max_length=10)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='grade',
            name='quarter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='grades.quarter'),
        ),
        migrations.AlterField(
            model_name='observedvalue',
            name='quarter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='grades.quarter'),
        ),
    ]
