# Generated by Django 5.0 on 2024-01-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_quarter_alter_semester_name_grade_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core'), ('applied', 'Applied'), ('specialized', 'Specialized')], default='core', max_length=20),
        ),
    ]
