# Generated by Django 5.0 on 2024-01-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_behaviorstatement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedvalue',
            name='grade',
            field=models.CharField(choices=[('AO', 'AO'), ('SO', 'SO'), ('RO', 'RO'), ('NO', 'NO')], max_length=3),
        ),
    ]
