# Generated by Django 5.0 on 2023-12-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('complete_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_cert', models.BooleanField(default=False, verbose_name='Birth Certificate')),
                ('attendance', models.IntegerField(default=0, verbose_name='Daily Attendance')),
            ],
        ),
    ]
