# Generated by Django 5.0 on 2024-01-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitymonitoring', '0001_initial'),
        ('grades', '0003_alter_observedvalue_grade'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('WW', 'Written Work'), ('PT', 'Performance Task'), ('QE', 'Quarter Exam')], max_length=20),
        ),
        migrations.CreateModel(
            name='Student_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitymonitoring.student_activity'),
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitymonitoring.student_activity')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.subject')),
            ],
        ),
        migrations.AddField(
            model_name='student_activity',
            name='subjects',
            field=models.ManyToManyField(through='activitymonitoring.SubjectEnrollment', to='grades.subject'),
        ),
    ]
