# Generated by Django 5.0 on 2024-01-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitymonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
