# Generated by Django 5.0 on 2024-01-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitymonitoring', '0002_alter_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activitymonitoring.section'),
            preserve_default=False,
        ),
    ]
