# Generated by Django 5.0 on 2023-12-31 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.advisory')),
            ],
        ),
    ]
